# Generated by Django 3.1.7 on 2021-03-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_earning_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earning',
            old_name='amount',
            new_name='money',
        ),
    ]
