# Generated by Django 3.1.7 on 2021-03-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210326_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='money_earned',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Earning',
        ),
    ]
