# Generated by Django 3.1.7 on 2021-03-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210327_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='person',
        ),
    ]
