# Generated by Django 3.1.7 on 2021-03-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210327_0332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
